### ISSUE TITLE
Please help!

### ISSUE THREAD

**Issue by YIRU69** [SimeonLukas/obsidian-kindle-export#1]
Thanks for you share!
And I try to use you Plugin that I have some problem.
I have not my own Backend , and use the (https://staneks.de/apps/md2mobi/) as Backend 
My kindle get file but it looks a certain amout of odd!
There some picture 
![6dc1625ded08e65145ce35bd5c52c2e](https://user-images.githubusercontent.com/48148292/158091932-7cab7f6f-b898-410c-89d8-86978dc00cbb.jpg)
![Snipaste_2022-03-14_09-57-41](https://user-images.githubusercontent.com/48148292/158091943-b7b011ec-6be6-4ad6-8156-e1baca253aac.png)
![Snipaste_2022-03-14_09-58-02](https://user-images.githubusercontent.com/48148292/158091947-2ffaca1c-2562-4a2b-8c1f-d769b3291968.png)

**Comment by SimeonLukas** [comment]
Hi YIRU69,

Thank you for sending me this issue.
And I'm sorry its looking odd.
I try to fix this.
May you send me this document with all attachments, you don't have to, but it would be easier to fix the problems.

Greetings and have a nice day,
Simeon

**Comment by SimeonLukas** [comment]
Hi YIRU69,

I updated the plugin.
Do you want to try the new version 0.0.5?
I hope this will fix some of the problems.

Greetings,
Simeon

**Comment by YIRU69** [comment]
I'm very glad to listen this message!
I can try it and reply quickly

**Comment by YIRU69** [comment]
year, you improve the "%%--%%",but image also can't show.
Updata my file and hope it can help you.
[🅰Word-enamor.pdf](https://github.com/SimeonLukas/obsidian-kindle-export/files/8243278/Word-enamor.pdf)

**there have some picture when I try again!**

![3e22949ee9e2e25a032d27a3bcf8668](https://user-images.githubusercontent.com/48148292/158138777-b970b1f7-0a91-49d6-8da3-251bdfab1336.jpg)
![ca9f900bfedfc25962cbebf8ccdf84e](https://user-images.githubusercontent.com/48148292/158138787-d8e92c6b-bed2-4e0f-96fa-57988372b2c8.jpg)

**Comment by SimeonLukas** [comment]
Thank you for your patience.
May you send me the markdown code?

Sorry for the problems!

Greetings,
Simeon

**Comment by YIRU69** [comment]
I have some advice for this plugin.
Have a page break on kindle export when you put "---", just like it https://forum.obsidian.md/t/meta-post-common-css-hacks/1978/357

[🅰Word-enamor.md](https://github.com/SimeonLukas/obsidian-kindle-export/files/8243334/Word-enamor.md)

Greetings

**Comment by SimeonLukas** [comment]
Hi YIRU69,

thanks for your advice and for the document!

1. ```%%Break%% <div style="page-break-after: always;"></div>```| This is meant to make an pagebreak. But I'm going to implement a toggle switch to allow a pagebreak by '---'.
2. I try to fix the problem. I hope you have the patience.

Greetings,
Simeon

**Comment by YIRU69** [comment]
I'm looking forward to hearing from you.

**Comment by SimeonLukas** [comment]
Hi YIRU69,

Now it should work.
I made the same file you have. There was an issue by not embed linked files.
This was a major issue! So thank u very much for your help!
Please update to version 0.0.6.
I added a toggle for breaking at ---.
So now you can use this feature.
![1647283235878](https://user-images.githubusercontent.com/33984591/158239401-99f8fc6d-6f75-4602-b7a3-bd5c54df630c.jpg#right||test|200)

Please tell me if its now working for you.

Greetings,
Simeon

**Comment by YIRU69** [comment]
Thank you Thank you Thank you 
hahahah

**Comment by YIRU69** [comment]
And I find the hightlight don't work.

**Comment by SimeonLukas** [comment]
Good morning,
This will be a feature in the next update.
I'm working on it, but it is kind of tricky, because .mobi file don't understand the <mark> tag. 
So I'm going to underline it or something else.

Greetings,
Simeon

**Comment by YIRU69** [comment]
Good afternoon sir!
Have a nice day, and help you plugin become better!
