### ISSUE TITLE
Feature request: Option to Download epub if sending fails

### ISSUE THREAD

**Issue by martinmenge** [SimeonLukas/obsidian-kindle-export#11]
It would be nice to have the option to download the epub if there is an SMTP failure.

**Comment by SimeonLukas** [comment]
Hi martinmenge,

Really good idea.
I try my Best!
Greetings,
Simerl

**Comment by mkerd** [comment]
How about directly having that option before attempting to send?

**Comment by SimeonLukas** [comment]
I'll try my Best.
I'm going to add the feature soon.

**Comment by SimeonLukas** [comment]
Hithere,
I made some changes to the Endpoint:
https://github.com/SimeonLukas/Obsidian2Kindle

You can try it.
Just change it in the Settings of Obsidian:

https://md2epub.staneks.de/

I hope this helps.

Now you can Download and share all converted .epub files.
These files are available for one day (until midnight).

Grettings
Simeon
