### ISSUE TITLE
tags as headers problem

### ISSUE THREAD

**Issue by BenWaw** [SimeonLukas/obsidian-kindle-export#13]
I have #tags in my notes and when I export them, they convert to # HEADERS and because of that, it splits the whole chapter into pieces.

**Comment by SimeonLukas** [comment]
Hi BenWaw,

Sorry for this bug.
I'm going to fix this.
Greetings Simerl

**Comment by SimeonLukas** [comment]
Hithere,

I made the fix.
Thanks for your Issue!
Now it should work.

https://github.com/SimeonLukas/Obsidian2Kindle/commit/17d79d910b3fbe5bd963821088f2ae8496334143

Greetings
