### ISSUE TITLE
Coild not connect to SMTP host

### ISSUE THREAD

**Issue by EntropicNinja** [SimeonLukas/obsidian-kindle-export#14]
Hello,

I'm using Mailer send and have the plugin on my android device. I can download the epub with the newer backend, but am getting the error as seen below.

I know MailerSend has disabled TLS v1.0 and wondered if that has anything to do with this?

![Screenshot_20240724-235808_1](https://github.com/user-attachments/assets/ee9623bb-bfc0-49aa-9214-4b1c2481cc88)

**Comment by SimeonLukas** [comment]
Hithere,

is the Port correct?

Greetings 
Simerl

**Comment by EntropicNinja** [comment]
I am, yes. I'm using mailersend.net and was told to use 587.

**Comment by EntropicNinja** [comment]
I am, yes. I'm using mailersend.net and recommended to use port 587.

Apologies, I did not mean to close this issue.

**Comment by SimeonLukas** [comment]
So are the credentials correct?

I'm not using Mailersend, but the error occurs most by setting the wrong credentials.

I'm sorry
