### ISSUE TITLE
Export embedded .md files command

### ISSUE THREAD

**Issue by codeMonkeyWang** [SimeonLukas/obsidian-kindle-export#2]
can you add a command： Export embedded .md files

**Comment by SimeonLukas** [comment]
Hi CodeMonkeyWang,

You mean a command to export all embedded .md files as single Book to the Kindle?

Greetings,
Simeon

**Comment by codeMonkeyWang** [comment]
I need  embedded .md files export to  standard md  files feature ,in other plugin not find it。

**Comment by codeMonkeyWang** [comment]
> Hi CodeMonkeyWang,
> 
> You mean a command to export all embedded .md files as single Book to the Kindle?
> 
> Greetings, Simeon

I need embedded .md files export to standard md files feature ,in other plugin not find it.

forgive me my English is so poor

**Comment by SimeonLukas** [comment]
Good Evening CodeMonkeyWang,

Now I understand.
This will extend the Plugin way over the core features, but I'm going to make a toggle switch in the Settings. This will add the command Kindle: Mergedown.

I'll try my best.

Greetings from Bavaria

**Comment by SimeonLukas** [comment]
Hi codeMonkeyWang,

So I made an update.
Please update your Kindle Export to v0.0.9.
Now you can merge embedded images and .md files into one file.
In the settings is a switch called: Markdown merge.
This will reload the plugin and then you have the mergedwon command in your commandlist.

Please try it. I hope it makes no issues.
Greetings
Simeon

**Comment by codeMonkeyWang** [comment]
> Hi codeMonkeyWang,
> 
> So I made an update. Please update your Kindle Export to v0.0.9. Now you can merge embedded images and .md files into one file. In the settings is a switch called: Markdown merge. This will reload the plugin and then you have the mergedwon command in your commandlist.
> 
> Please try it. I hope it makes no issues. Greetings Simeon

it work thinkyou
but，I hope I can set the Export path

**Comment by SimeonLukas** [comment]
Ok I will add this in the settings.I'll tell you then.

Greetings,
Simeon

**Comment by SimeonLukas** [comment]
Is done.
I hope this helps.
Have a nice day!
Greetings,
Simeon
