### ISSUE TITLE
Bug: export error

### ISSUE THREAD

**Issue by YIRU69** [SimeonLukas/obsidian-kindle-export#3]
Hi, friend, 
I'm try to use the plugin on  ob vision 0.15.6

![image](https://user-images.githubusercontent.com/48148292/178890925-655b4544-8067-43e4-afd1-40fc65dc3bec.png)
[英语句子摘录.md](https://github.com/SimeonLukas/obsidian-kindle-export/files/9108147/default.md)

**Comment by SimeonLukas** [comment]
Hi YIRU,

You should update, the server software.
.mobi won't work anymore in August.
I made an update to the server software.
[New Version](https://github.com/SimeonLukas/Obsidian2Kindle)
The software is going to make an .epub file.
This is now going to work I hope.
Greetnigs,
Simerl

**Comment by YIRU69** [comment]
HI, it is also meet the problem.
![image](https://user-images.githubusercontent.com/48148292/178932601-b089dc94-3175-420c-b078-112915c1ebcb.png)

**Comment by SimeonLukas** [comment]
Did you put this file: [File](https://github.com/SimeonLukas/Obsidian2Kindle/blob/main/obsidian-kindle-export-2022.png) in the directory?

**Comment by YIRU69** [comment]
yeah, put it on 
![image](https://user-images.githubusercontent.com/48148292/178933869-b1539afb-e73f-4782-b29e-1b90b36dea34.png)

**Comment by SimeonLukas** [comment]
Did you check the permissions of the file?

**Comment by YIRU69** [comment]
yeah, I just  overwrite `https://github.com/SimeonLukas/Obsidian2Kindle` files.

**Comment by YIRU69** [comment]
and try again, it disapper the same error
![image](https://user-images.githubusercontent.com/48148292/178937453-da19fcd3-09d8-4d12-970c-3c6f48e4d012.png)

**Comment by SimeonLukas** [comment]
ob vision 0.15.6 is a Docker Container?

can you create an "uploads" folder in the directory?
And I think you need a linebreak before the .mp3 files.

I hope this helps.

**Comment by YIRU69** [comment]
ob vision 0.15.6
I make a linebreak before the .mp3 files. and it also have a same error.

**Comment by YIRU69** [comment]
1. md file
![image](https://user-images.githubusercontent.com/48148292/178940207-ff518709-f919-4b18-b9fa-e3838ba29123.png)

2. error output
![image](https://user-images.githubusercontent.com/48148292/178940278-3382e4a5-bff3-40d0-8435-0335417c7ec8.png)

**Comment by SimeonLukas** [comment]
I made a change to [index.php](https://raw.githubusercontent.com/SimeonLukas/Obsidian2Kindle/main/index.php)

Can you try this?

Greetings

**Comment by YIRU69** [comment]
It seem to work. May be I have to do many test
![image](https://user-images.githubusercontent.com/48148292/178941778-60c70199-9bf8-40e1-ac85-92c0f84ae433.png)

**Comment by SimeonLukas** [comment]
Ok I hope this works!

**Comment by YIRU69** [comment]
@SimeonLukas Thank your patient.
I think, would you add a choose that export file in the local.

**Comment by SimeonLukas** [comment]
you are welcome.

you can uncomment this part:

` 204 unlink('epubs/' . $_POST['title'].'.epub');`
to
`204 //unlink('epubs/' . $_POST['title'].'.epub');`

so your .epub will stay in the epubs folder.

In future I'll try to make it easier.

Greetings,
Simerl

**Comment by YIRU69** [comment]
Thank you friend. I hope you can finish you plan about the plugin. About export html etc..

**Comment by SimeonLukas** [comment]
Thank you I try my best.
And thank you for your testing and patience!
Greetings,
Simeon

**Comment by YIRU69** [comment]
Unfortunatelly, it can't solve the problem what I post the issue.
And the STMP has the problem above the picture.
The export file have nothing content except heading.
Test for [英语句子摘录.md](https://github.com/SimeonLukas/obsidian-kindle-export/files/9108147/default.md)

**Comment by SimeonLukas** [comment]
For the problem of the smtp i can't help it is an issue of [phpmailer](https://github.com/PHPMailer/PHPMailer).
Are your credentials correct?

The other problem occurs because of the missing linebreaks before the .mp3 files.
This file should work.
[fix.md](https://github.com/SimeonLukas/obsidian-kindle-export/files/9111087/fix.md)

**Comment by YIRU69** [comment]
ok I will try it later.

**Comment by SimeonLukas** [comment]
Hi Yiru69,

Does it now work for you?

Greetings

**Comment by YIRU69** [comment]
> Hi Yiru69,
> 
> Does it now work for you?
> 
> Greetings

Sorry，later to reply. It work when I try again. Thank you.
