### ISSUE TITLE
There was a problem with the document(s) that you sent to Kindle

### ISSUE THREAD

**Issue by creadian** [SimeonLukas/obsidian-kindle-export#4]
Dear Simeon, 

I can't send files to kindle anymore, I get the following error message:

Dear Kindle Customer,

The following document, sent by you at 16:16 Uhr, am Sonntag, 21. August 2022 MESZ, could not be delivered to the address you specified:

* test for kindle.epub

I'm using your plugin with default settings, and with your backend. 
Are there any issues with the recent change from mobi to epub?
Thanks a lot for your great plugin, it has been super helpful to me :-)

**Comment by SimeonLukas** [comment]
Dear creadian,

I'm sorry for this Problem. I hope I can find the Issue.
Can you send me the .md file and the exported .epub file?
In my case, the Plugin and Backend are working.
I use the Backend: https://staneks.de/apps/md2mobi/

Is the Email account, you send from, approved by Amazon, or is the @kindle.com Email right?

Greetings,
Simeon

**Comment by creadian** [comment]
Hi Simeon, sure, I can send you the md and epub. Is there an email I can send it to? From mobile, I can't upload files to github

**Comment by SimeonLukas** [comment]
Sure.
Please send it to rtdust@gmail.com.
Greetings,
Simeon

**Comment by creadian** [comment]
Sorry for the delay, I just sent you the files for checking. thank you so much for looking into it!

**Comment by SimeonLukas** [comment]
Hi creadian,

I hope the problem is solved.
There was an Issue with the locaStorage Key 'language'.

I hope it works for you.

Please install the Update 0.0.11.

Greetings,
Simeon
