### ISSUE TITLE
I am getting SMTP connect Fail Error

### ISSUE THREAD

**Issue by mahadevan** [SimeonLukas/obsidian-kindle-export#5]
![12-10 Wednesday 01](https://user-images.githubusercontent.com/2020804/195273139-3aaaa99a-43ca-415b-ad55-6ff2ba84c560.png)

I have PHP 8 installed. 

I am getting an "SMTP Connect Fail Error". I am using port 587. Gmail as SMTP Provider ("smtp.gmail.com")

nb: I have XAMPP installed. Is it necessary to install PHPmailer separately for this plugin to work?

**Comment by mahadevan** [comment]
While using port 465

![image](https://user-images.githubusercontent.com/2020804/195785502-43d37b21-341b-49a4-b726-3f62fff572ee.png)

**Comment by SimeonLukas** [comment]
Hi mahadevan,

I'm sorry for this problem.
This is an Issue for [PHP-Mailer](https://github.com/PHPMailer/PHPMailer).

Do have Two-Factor-Auth enabled and an extra APP-Password created with the Google-UI?
[Google-Apppassword](https://support.google.com/accounts/answer/185833?hl=de)

[Issue PHP-Mailer](https://github.com/PHPMailer/PHPMailer/issues/2695)

Greetings,
Simeon

**Comment by SimeonLukas** [comment]
Is your Problem fixed?
Greetings,
Simeon

**Comment by mahadevan** [comment]
> Is your Problem fixed? Greetings, Simeon

Nope, I just tried again.

![image](https://user-images.githubusercontent.com/2020804/198350966-c8bcb2ac-22a1-4cac-a0aa-98424a2191d0.png)

![27-10 Thursday 01](https://user-images.githubusercontent.com/2020804/198351465-03deb8b6-6957-4e49-a936-891957893e2a.png)

What are the prerequisites? I have windows 11, PHP installed. 

![27-10 Thursday 02](https://user-images.githubusercontent.com/2020804/198351891-1f08da11-f9db-41e8-8b8a-ca3d6fa50d56.png)

Do I need to install anything else? I am able to push files to kindle via chrome extension & caliber.

**Comment by SimeonLukas** [comment]
Ok does it work with this Backendaddress?
https://staneks.de/apps/md2mobi/

Greetings,
Simeon

**Comment by mahadevan** [comment]
I use "https://staneks.de/apps/md2mobi/" on the settings

![image](https://user-images.githubusercontent.com/2020804/198642785-0ef03140-9381-46b6-a99b-df44b2fd6dd4.png)

It doesn't work. Also, Kindle has stopped support for mobi format & azw3 & epub works. But I don't think it was the problem as in the such case I would receive an email from kindle that it couldn't send files to my Kindle device. I didn't any such mail.

**Comment by mahadevan** [comment]
Also "https://staneks.de/apps/md2mobi/" gives this

![28-10 Friday 03](https://user-images.githubusercontent.com/2020804/198645924-3d478aa1-3033-4309-9204-967ab7b1e220.png)

**Comment by SimeonLukas** [comment]
Yeah the Warnings are just normal, when you open the Address in the Browser. I'm going to change this in the future.

There is still a problem with your credentials. Do you have an extra App-Password for your Google account?

Greetings

**Comment by Mamonbo** [comment]
I got the same authentication error too.
So I read this issue and created an App-Password and changed this plugin settings as follows:
SMTP Port : 465 (SSL port not TLS / STARTTLS port in Gmail)
SMTP Password : _App-Password_

Then it worked.

I don't know this is the best soluttion regarding security though.

**Comment by mahadevan** [comment]
> Yeah the Warnings are just normal, when you open the Address in the Browser. I'm going to change this in the future.
> 
> There is still a problem with your credentials. Do you have an extra App-Password for your Google account?
> 
> Greetings
@SimeonLukas Solved.
I used a different Gmail ID & App Password. Changed the socket to 465. It solved the issue. Thanks for the help.

**Comment by SimeonLukas** [comment]
Great 👍
