### ISSUE TITLE
Bug: footnote can't export to kindle

### ISSUE THREAD

**Issue by YIRU69** [SimeonLukas/obsidian-kindle-export#6]
Hi ,friend. 
Can you try to export md file to kindle with footnote?
I use it and can't display right on my kindle. 
Please check it out if you have free time.

**Comment by SimeonLukas** [comment]
Hi Yiru69,

Sure do u have a example file for me?
I never worked with footnotes.

Greetings,
Simeon

**Comment by YIRU69** [comment]
[example-kindle.md](https://github.com/SimeonLukas/obsidian-kindle-export/files/9807116/example-kindle.md)
@SimeonLukas

**Comment by SimeonLukas** [comment]
Hi YIRU69,

I updated the Backend.
So now it should work.
The Links are working too, unless you have no Headline or "---" between Links and Notes.

I hope you like it.

Greetings,
Simeon

**Comment by YIRU69** [comment]
Thank you very much !
