### ISSUE TITLE
Mergedown crashes when there is a circular reference

### ISSUE THREAD

**Issue by Mamonbo** [SimeonLukas/obsidian-kindle-export#8]
Mergedown command expands embedded markdown file. So when there is a circular reference (written in the embedding format), it seems to expand infinitely.

Here is the minimum example (suppose that the filename is self.md):
`![[self.md]]`

**Comment by SimeonLukas** [comment]
Thank you very much for the Issue.

I hope it works now in the new Update 0.0.13.

Greetings,
Simeon
