### ISSUE TITLE
Private API deprecation

### ISSUE THREAD

**Issue by lishid** [SimeonLukas/obsidian-kindle-export#9]
Hello! We noticed that you're using an undocumented Obsidian function in your plugin that we'll likely be changing soon. I highly suggest making a replacement for it from public API instead of relying on it!

The API you were using is `fileManager.getAllLinkResolutions()`.

```ts
// Old
let AllLinks = this.app.fileManager.getAllLinkResolutions();
for (let i = 0; i < AllLinks.length; i++) {
	if (AllLinks[i].sourceFile.path == dokument.path) {
		links.push(AllLinks[i]);
	}
}
```
```ts
// New
this.app.metadataCache.iterateReferences((sourcePath: string, reference: ReferenceCache) => {
	if (sourcePath == dokument.path) {
		links.push(reference);
	}
});
```

**Comment by SimeonLukas** [comment]
Thank you very much for the Example.
I made the Changes.

Greetings,
Simeon
